import { getFiles } from "@/app/actions/drive";
import { SearchFiles } from "@/components/SearchFiles";

export default async function AdminFilesPage() {
  const files = await getFiles(500);

  return (
    <div className="p-4 sm:p-6 lg:p-10 max-w-5xl mx-auto">
      <header className="mb-6">
        <h1 className="text-2xl sm:text-3xl font-black text-white">Admin Files</h1>
        <p className="text-muted-foreground mt-1 text-sm">{files.length} total files generated by you.</p>
      </header>

      <SearchFiles initialFiles={files} />
    </div>
  );
}
